<?php

namespace AppBundle\Repository;

/**
 * AsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaRepository extends \Doctrine\ORM\EntityRepository{

	public function buscarPorTitulo($asignatura) {
		$asignatura = $this->findOneByTitulo($asignatura);
		return $asignatura;
	}

    public function buscarTodo() {
        
        $qb = $this->createQueryBuilder('a');
        $qb->where($qb->expr()->eq('a.publicado', 'true'))
            ->addOrderBy('a.orden', 'ASC')
        ;
        $asignatura = $qb->getQuery()->getResult(); 

        return $asignatura;
    }    	
}
