<?php

namespace AppBundle\Repository;

/**
 * ConsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaRepository extends \Doctrine\ORM\EntityRepository {

	public function numConsultas($seccion) {
   		$qb = $this->createQueryBuilder('c');
        $qb->select('count(c)')
        	->where($qb->expr()->eq('c.seccion', ':seccion'))
        	->setParameter('seccion', $seccion);

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
	}

	public function buscarTodasSeccion($seccion) {
		$qb = $this->createQueryBuilder('c');
		$qb->where($qb->expr()->eq('c.seccion', ':seccion')) 
			->setParameter('seccion', $seccion)
			->addOrderBy('c.fecha', 'ASC');

		$consultas = $qb->getQuery()->getResult();

	    return $consultas;
	}
}
