<?php

namespace AppBundle\Repository;

/**
 * Foro_GeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Foro_GeneralRepository extends \Doctrine\ORM\EntityRepository
{
}
