<?php

namespace AppBundle\Repository;

/**
 * FraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraseRepository extends \Doctrine\ORM\EntityRepository {

	function buscarTodo() {
		
		$qb = $this->createQueryBuilder('f');
		$qb->where($qb->expr()->eq('f.publicado', 'true'))
			->orderBy('f.id', 'ASC');
		$frases = $qb->getQuery()->getResult(); 
		
        return $frases;
	}
}
