<?php

namespace AppBundle\Repository;

/**
 * Matricula_ServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class Matricula_ServiciosRepository extends \Doctrine\ORM\EntityRepository {

    public function isMatriculado($servicio, $usuario) {

        $qb = $this->createQueryBuilder('ms');                 
        $qb->where($qb->expr()->andX(
                'ms.servicio = :servicio',
                'ms.usuario = :usuario'
        ))
        ->setParameter('servicio', $servicio)
        ->setParameter('usuario', $usuario);

        $ms = $qb->getQuery()->getResult();

        $matriculado = (count($ms)) ? true : false;

        return $matriculado;
    }
}
