<?php

namespace AppBundle\Repository;

/**
 * Matricula_TemariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Matricula_TemariosRepository extends \Doctrine\ORM\EntityRepository {

        public function isMatriculado($temario, $usuario) {

                $qb = $this->createQueryBuilder('mt');                 
                $qb->where($qb->expr()->andX(
                        'mt.temario = :temario',
                        'mt.usuario = :usuario'
                ))
                ->setParameter('temario', $temario)
                ->setParameter('usuario', $usuario);

                $mt = $qb->getQuery()->getResult();
        
                $matriculado = (count($mt)) ? true : false;

                return $matriculado;

        }

}
