<?php

namespace AppBundle\Repository;

/**
 * Matricula_TemariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Matricula_TemariosRepository extends \Doctrine\ORM\EntityRepository
{
}
