<?php

namespace AppBundle\Repository;

/**
 * Matricula_SeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Matricula_SeccionesRepository extends \Doctrine\ORM\EntityRepository {

    public function isMatriculado($seccion, $usuario) {

        $qb = $this->createQueryBuilder('ms');                 
        $qb->where($qb->expr()->andX(
                'ms.seccion = :seccion',
                'ms.usuario = :usuario'
        ))
        ->setParameter('seccion', $seccion)
        ->setParameter('usuario', $usuario);

        $ms = $qb->getQuery()->getResult();

        $matriculado = (count($ms)) ? true : false;

        return $matriculado;

	}
}
