<?php

namespace AppBundle\Repository;

/**
 * Opcion_PreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Opcion_PreguntaRepository extends \Doctrine\ORM\EntityRepository {

	public function buscarPorPregunta($pregunta) {

        $qb = $this->createQueryBuilder('o');                 
        $qb->where($qb->expr()->eq('o.pregunta_examen', ':pregunta'))
        	->setParameter('pregunta', $pregunta)
   			->addOrderBy('o.orden', 'ASC');
        
        $opciones = $qb->getQuery()->getResult();

        return $opciones;
	}	
}
