<?php

namespace AppBundle\Repository;

/**
 * Opcion_PreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Opcion_PreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
