<?php

namespace AppBundle\Repository;

/**
 * Pregunta_ExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pregunta_ExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
