<?php

namespace AppBundle\Repository;

/**
 * SeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionRepository extends \Doctrine\ORM\EntityRepository {

	public function buscarFrase($frase) {

        $qb = $this->createQueryBuilder('s');                 
        $qb->where(
        	$qb->expr()->orX(
        		$qb->expr()->like('s.titulo', '?1'),
        		$qb->expr()->like('s.descripcion', '?1')
        	)
        )
		->setParameter(1, '%'.$frase.'%')
   		->addOrderBy('s.orden', 'ASC');
        $secciones = $qb->getQuery()->getResult();

        return $secciones;
	}	

    public function buscar($id) {
        $seccion = $this->find($id);
        return ($seccion && $seccion->getPublicado()) ? $seccion : null;
    }

    // devuelve todas las secciones activas del temario dado
    public function buscarTodos($temario) {
        
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->andX(
                $qb->expr()->eq('s.publicado', 'true'),
                $qb->expr()->eq('s.temario', ':temario')
            )
        )
        ->setParameter('temario', $temario)
        ->addOrderBy('s.orden', 'ASC');

        $secciones = $qb->getQuery()->getResult(); 

        return $secciones;
    }       
}
