<?php

namespace AppBundle\Repository;

/**
 * SeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionRepository extends \Doctrine\ORM\EntityRepository {

	public function buscar($frase) {

        $qb = $this->createQueryBuilder('s');                 
        $qb->where(
        	$qb->expr()->orX(
        		$qb->expr()->like('s.titulo', '?1'),
        		$qb->expr()->like('s.descripcion', '?1')
        	)
        )
		->setParameter(1, '%'.$frase.'%')
   		->addOrderBy('s.orden', 'ASC');
        $secciones = $qb->getQuery()->getResult();

        return $secciones;
	}	
}
