<?php

namespace AppBundle\Repository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends \Doctrine\ORM\EntityRepository {

	public function buscar($frase) {

        $qb = $this->createQueryBuilder('s');                 
        $qb->where(
        	$qb->expr()->orX(
        		$qb->expr()->like('s.titulo', '?1'),
        		$qb->expr()->like('s.descripcion', '?1')
        	)
        )
		->setParameter(1, '%'.$frase.'%')
		->addOrderBy('s.prioridad', 'ASC')
   		->addOrderBy('s.fechaIni', 'DESC');
        $servicios = $qb->getQuery()->getResult();

        return $servicios;
	}
}
