<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Servicio;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends \Doctrine\ORM\EntityRepository {

	public function buscarFrase($frase) {

        $qb = $this->createQueryBuilder('s');                 
        $qb->where(
            $qb->expr()->andX(
                $qb->expr()->eq('s.publicado', 'true'),
                $qb->expr()->orX(
        		  $qb->expr()->like('s.titulo', ':frase'),
        		  $qb->expr()->like('s.descripcion', ':frase')
                )
        	)
        )
        ->setParameter('frase', '%'.$frase.'%')
		  ->addOrderBy('s.prioridad', 'ASC')
   		  ->addOrderBy('s.fechaIni', 'DESC');
        $servicios = $qb->getQuery()->getResult();

        return $servicios;
	}

    public function buscarTodo() {
        
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->eq('s.publicado', 'true'))
            ->addOrderBy('s.prioridad', 'ASC')
            ->addOrderBy('s.fechaIni', 'DESC')
        ;
        $servicios = $qb->getQuery()->getResult(); 

        return $servicios;
    }    

    public function ocultarServicios() {

        $fecha = new \Datetime();
        $qb = $this->createQueryBuilder('s');
        $qb->update(Servicio::class, 's')
            ->set('s.publicado', 'false')
            ->where($qb->expr()->gt('s.fechaIni', ':fecha'))
            ->setParameter('fecha', $fecha->format('Y-m-d H:i:s'))            
        ;
        
        $qb->getQuery()->execute(); 
    }

}
