<?php

namespace AppBundle\Repository;

/**
 * TemarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemarioRepository extends \Doctrine\ORM\EntityRepository {

	public function buscar($id_temario) {
		$temario = $this->find($id_temario);
		return $temario;
	}	

	// devuelve todos los temarios activos de la asignatura dada
    public function buscarTodos($asignatura) {
        
        $qb = $this->createQueryBuilder('t');
        $qb->where($qb->expr()->andX(
        		$qb->expr()->eq('t.publicado', 'true'),
        		$qb->expr()->eq('t.asignatura', ':asignatura')
        	)
    	)
		->setParameter('asignatura', $asignatura)
        ->addOrderBy('t.orden', 'ASC');

        $temarios = $qb->getQuery()->getResult(); 

        return $temarios;
    } 

}
