<?php

namespace AppBundle\Repository;

/**
 * TemarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemarioRepository extends \Doctrine\ORM\EntityRepository {

	function buscar($id_temario) {
		$temario = $this->find($id_temario);
		return $temario;
	}	
}
