seguridad:
    resource: "@SeguridadBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout

# el enrutamiento dentro de AppBundle será por anotación
app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    