<?php

namespace AppBundle\Service;

use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class FileUploader {

    private $extension = null;

    private function generateUniqueFileName() {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    public function getDirectorio($asignatura) {
        return 'documentos/'.$asignatura->getTitulo();
    }

    public function getExtension() {
        return $this->extension;
    }

    // método que guarda un fichero en una url y devuelve el nombre del fichero
    public function upload(UploadedFile $file, $asignatura) {

        // cargamos el sistema de ficheros
        $fileSystem = new Filesystem();

        // si no existe el directorio de la asignatura se crea.
        // al indicar 'documentos/' lo estamos creando en la raiz del directorio /web del sistema
        // si quisiéramos que se creara con url absolutas deberiamos indicar '/url/documentos'
        if (!$fileSystem->exists($this->getDirectorio($asignatura))) {
            $fileSystem->mkdir($this->getDirectorio($asignatura));
        }

        // otenemos la extensión del fichero, y creamos un nombre al hazar
        $this->extension = $file->guessExtension();
        $fileName = $this->generateUniqueFileName();

        // Guardamos el fichero con su nuevo nombre y extensión
        $file->move($this->getDirectorio($asignatura), $fileName.'.'.$this->extension);

        return $fileName;
    }

}